using System.Collections;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

public class playerMovement : MonoBehaviour
{
    public int health = 100;
    [SerializeField]private float speed = 5.0f;
    [SerializeField]private float jumpForce = 10.0f;
    [SerializeField]private Transform groundCheck;
    [SerializeField]private float groundCheckRadius = 0.2f;
    private SpriteRenderer spriteRenderer;
    private int extrajumps;
    public int extrajumpsvalue = 1;
    public LayerMask groundLayer;
    private bool isGrounded;
    private Rigidbody2D rb;
    private Animator animator;
    public Image healthbar;
    void Start()
    {
        rb = GetComponent<Rigidbody2D>();
        animator = GetComponent<Animator>();
        spriteRenderer = GetComponent<SpriteRenderer>();
        extrajumps = extrajumpsvalue;
    }

    // Update is called once per frame
    void Update()
    {
        float moveInput = Input.GetAxis("Horizontal");
        rb.linearVelocity = new Vector2(moveInput * speed, rb.linearVelocity.y);
        if (isGrounded)
        {
            extrajumps = extrajumpsvalue;
        }
        if (Input.GetKeyDown(KeyCode.Space))
        {
            if (isGrounded)
            {
                rb.linearVelocity = new Vector2(rb.linearVelocity.x, jumpForce);
            }
            else if (extrajumps > 0)
            {
                rb.linearVelocity = new Vector2(rb.linearVelocity.x, jumpForce);
                extrajumps--;
            }
            getanimation(moveInput);
        }
        healthbar.fillAmount = health / 100f;

    }

    private void FixedUpdate()
    {
        isGrounded = Physics2D.OverlapCircle(groundCheck.position, groundCheckRadius, groundLayer);
    }
    private void OnCollisionEnter2D(Collision2D collision)
    {
       if (collision.gameObject.CompareTag("damage"))
        {
            health -= 25;
            rb.linearVelocity = new Vector2(rb.linearVelocity.x, jumpForce);
            StartCoroutine(blinkRed());

            if (health <= 0)
            {
                Die();
            }
        }
    }

    private IEnumerator blinkRed()
    {
        spriteRenderer.color = Color.red;
        yield return new WaitForSeconds(0.2f);
        spriteRenderer.color = Color.white;
    }

    private void Die()
    {
        SceneManager.LoadScene(1);
    }

    private void getanimation(float moveInput)
    {
        if (isGrounded)
        {
            if (moveInput == 0)
            {
                animator.Play("player_idle");
            }
            else
            {
                animator.Play("player_run");
            }

        }
        else
        {
            if (rb.linearVelocityY > 0)
            {
                animator.Play("player_jump");
            }
            else
            {
                animator.Play("Player_fall");
            }
        }
    
    }
}
